services:
  weatherservice:
    build: ./WeatherService
    image: server-weatherservice:latest
    env_file:
      - ./WeatherService/.env
    ports:
      - "8080:8080"

  roomservice:
    build: ./RoomService
    image: server-roomservice:latest
    env_file:
      - ./RoomService/.env
    ports:
      - "8081:8081"

  bookingservice:
    build: ./BookingService
    image: server-bookingservice:latest
    env_file:
      - ./BookingService/.env
    ports:
      - "8082:8082"
    depends_on:
      - roomservice
      - weatherservice

  apigateway:
    build: ./API-Gateway
    image: server-apigateway:latest
    env_file:
      - ./API-Gateway/.env
    ports:
      - "8000:8000"
    depends_on:
      - bookingservice

  frontend:
    build: ./frontend
    image: server-frontend:latest
    depends_on:
      - apigateway

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./caddy/certs:/etc/caddy/certs:ro
    depends_on:
      - frontend
    
volumes:
  caddy_data: {}
  caddy_config: {}
