services:
  weatherservice:
    build: ./weatherService
    ports:
      - "8080:8080"

  roomservice:
    build: ./roomService
    ports:
      - "8081:8081"

  bookingservice:
    build: ./bookingService
    ports:
      - "8082:8082"
    depends_on:
      - roomservice
      - weatherservice

  apigateway:
    build: ./API-Gateway
    ports:
      - "8000:8000"
    depends_on:
      - bookingservice

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - apigateway
    